modules/Event.lua
Added all the events that were added in 0.9.0
=> Added missing events

love_api.lua
Sorry if this isn't formatted to your specifications, I tried to take information straight from the wiki like the other ones, but it wasn't really as clear.
=> Added love.conf

love_api.lua
This should be the last one for a little while. (hopefully)
=> Added some forgotten options

modules/event/enums/Event.lua, modules/physics/enums/BodyType.lua, modules/physics/enums/JointType.lua
Some descriptions were missing, so I went ahead and added them.
=> Added missing descriptions to enums

love_api.lua, modules/graphics/types/Mesh.lua, modules/graphics/types/Texture.lua, modules/physics/types/Joint.lua, modules/physics/types/Shape.lua, specs/api_spec.lua
Also fixed one of the supertypes
=> Added subtypes

love_api.lua
This makes more sense than the original implementation in my opinion, as the function is love.conf
=> Move config to love.conf

love_api.lua
Accidentally left out the variants.
=> Correctly format function

love_api.lua
These things tend to work better when it's done over 1 commit, not 3
=> Hopefully the last fix

love_api.lua
Was missing, see: https://love2d.org/wiki/love.gamepadaxis
=> Added third argument to love.gamepadaxis callback

.gitignore, generator/devBuild.sh
Right now I am working on a redesign of the documentation. For faster and easier development I used a fixed repo rather than pulling the code everytime I wanted to build the index.html.
=> Added a bash script for easier development

modules/audio/Audio.lua, modules/audio/enums/EffectType.lua, modules/audio/enums/EffectWaveform.lua, modules/audio/enums/FilterType.lua, modules/audio/types/RecordingDevice.lua, modules/audio/types/Source.lua
Made sure that love.audio is up-to-date with LÖVE's source code.
There is stuff that isn't even documented in the wiki which I'll list down later in the comments.
Type checking and proof reading would be appreciated! :heart:
=> Finish love.audio

modules/graphics/Graphics.lua
As documented here : https://love2d.org/wiki/love.graphics.isActive
=> Adding graphics.isActive

love_api.lua
I checked with https://love2d.org/wiki/Config_Files and it says it's a
number there
=> Change window height to number

modules/graphics/Graphics.lua
=> Updated love.graphics.newImage

modules/graphics/Graphics.lua
The table argument is actually called settings in the [LOVE wiki](https://love2d.org/wiki/love.graphics.newImage).
=> Rename flags to settings in graphics.newImage

modules/math/types/Transform.lua
Like #115 but with `setMatrix`'s other variant, and `getMatrix`.
=> Fix other Transform matrix functions

README.md
Here is a link to the Lua language server's [repository](https://github.com/LuaLS/lua-language-server).
=> Add Lua language server to the list of Projects using LOVE-API

modules/window/Window.lua
=> Fix love.window.getDesktopDimensions return types

modules/graphics/Graphics.lua
The issue was first raised here: https://github.com/LuaCATS/love2d/issues/1
Let me know if I did everything correctly.
=> Add missing love.graphics.newText variant

modules/image/types/ImageData.lua
ImageData:setPixel can also accept a table of color values.
=> Add missing variant of ImageData:setPixel

modules/audio/Audio.lua
This fixes the return values as defined in the documentation
=> fix(Audio): Ungroup return values for getOrientation
